# Form implementation generated from reading ui file 'jt_add_athlete_dialog_designer.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(371, 321)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 260, 311, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 321, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.name_label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.name_label)
        self.name_lineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.name_lineEdit)
        self.left_right_label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.left_right_label.setObjectName("left_right_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.left_right_label)
        self.left_right_comboBox = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        self.left_right_comboBox.setObjectName("left_right_comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.left_right_comboBox)
        self.shank_length_label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.shank_length_label.setObjectName("shank_length_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.shank_length_label)
        self.shank_length_ineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.shank_length_ineEdit.setObjectName("shank_length_ineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.shank_length_ineEdit)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(30, 130, 311, 111))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.name_label.setText(_translate("Dialog", "Athletes name: "))
        self.left_right_label.setText(_translate("Dialog", "Injured leg:"))
        self.shank_length_label.setText(_translate("Dialog", "Shank length"))
        self.label.setText(_translate("Dialog", "Warning:  An athletes name can not be changed once created, type carefully!   To change the injured leg or shank length go to the config directory and carefully change their values in athletes.csv.  DO NOT change the the athletes name or the force will be disturbed..."))
